channels:
- conda-forge
dependencies:
- python=3.9.12
- pip<=22.1.2
- pip:
  - mlflow
  - cloudpickle==2.0.0
  - lz4==3.1.3
  - pathlib==1.0.1
  - psutil==5.9.0
  - scikit-learn==1.1.1
  - typing-extensions==3.7.4.3
name: mlflow-env
